name: build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install and build
        run: |
          npm ci
          npm run build
